name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        apollo-client: ["^3.8.0", "^4.0.0"]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
      - run: pnpm install --frozen-lockfile
      - name: Pin @apollo/client to ${{ matrix.apollo-client }}
        run: pnpm add --save-dev @apollo/client@${{ matrix.apollo-client }} graphql@^16.8.0
      - run: pnpm test
      - run: pnpm test:integration

  automerge:
    needs: [test, matrix]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
